-- Persistent reprocessing queue for @RvCommand(persistent = true) commands.
-- PENDING rows are picked up by the poller when next_attempt_at is due;
-- PROCESSING rows older than the processing timeout are reclaimed (crashed worker);
-- FAILED rows are the dead letter set - requeue manually with:
--   UPDATE rv_command_queue SET status = 'PENDING', attempts = 0 WHERE id = ...;
CREATE TABLE IF NOT EXISTS rv_command_queue (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command         VARCHAR(100)  NOT NULL,
    subject         VARCHAR(500)  NOT NULL,
    payload         CLOB          NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    attempts        INT           NOT NULL,
    max_attempts    INT           NOT NULL,
    next_attempt_at TIMESTAMP     NOT NULL,
    last_error      VARCHAR(2000),
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rv_command_queue_poll
    ON rv_command_queue (status, next_attempt_at);
